### ISSUE TITLE
Processing a SLAB-created file holding event data

### ISSUE THREAD

**Issue by JMerrill** [mspnp/semantic-logging#1]
(I copied this issue from the Codeplex site; no one had responded to it there.)

The documentation describes both in-process and out-of-process mechanisms for processing events as they occur, in real time. I was planning to update my application that now writes (rather unstructured) text messages to a file for examination later (via redirected Console output) so that it also writes the same events using SLAB. 

I was then planning to write an application that reads the resulting event file(s) and does different things with the different kinds of events. (That should be much easier than reading the text file and parsing the different barely-structured message formats that now exist in the pure text file.) This would be entirely asynchronous to the creation of the event files. 

For example, some things that are encountered could be "data problems" with the plan of sending an email to the users who entered bad data. Other things (like a failure to access the database or getting errors from a 3rd-party API) could be "processing problems" about which administrators should be notified. Performance data (how long different things take) could also be recorded, to build a profile of application performance to check for possible issues as data size increases. 

I have not seen anything that shows me how I can take a file produced by SLAB and treat it as an "event stream" for processing later. (I could surely do this if I built my own way of serializing structured copies of the event data and used it instead of SLAB.) Is that possible? 

Thank you for any information.

**Comment by JMerrill** [comment]
Is this not worthy of an answer?

**Comment by bennage** [comment]
@JMerrill My apologies. We've been distracted for the last several months and lot has slipped through cracks.

To address you question, there are lots different ways to handle what you want to do. 
One way would be to create a [custom sink](https://msdn.microsoft.com/en-us/library/dn775003(v=pandp.20).aspx) to pump the events to a services like [Event Hub](http://azure.microsoft.com/en-us/services/event-hubs/). Once the events are in event hub, you could write [an event processor](https://msdn.microsoft.com/en-us/library/dn789972.aspx) to do whatever custom logic that you would like. The custom sink could run either in-process or out-of-process. We encourage out-of-process when possible.

We have some example event processors in our [data-pipeline repo](https://github.com/mspnp/data-pipeline).

I hope this is helpful.

//cc @manikrish Do you have anything else to add?

**Comment by maniks418** [comment]
Using the event processor is definitely an option.
 If playback from a file is what you are looking for specifically you maybe able to achieve this using http://tx.codeplex.com/
I have not explored this project in detail but it appears to support playback of events from a file using Reactive Extensions.

**Comment by manikrish** [comment]
I posted my suggestion earlier using the wrong github account:

Using the event processor is definitely an option. If playback from a file is what you are looking for specifically you maybe able to achieve this using http://tx.codeplex.com/. I have not explored this project in detail but it appears to support playback of events from a file using Reactive Extensions.

**Comment by JMerrill** [comment]
Thank you for that. The disadvantage of using an Event Processor is that I have to complete that work, and ensure that it doesn't fail in a way that brings down the entire process being monitored, before I can start collecting data using SLAB. I wanted to start sending data with SLAB, which seems trivial for my code (all the hard stuff is in your code) and process it later.

If that can read the events from a file, I could probably use just that part of it -- or write my processing logic using Reactive Extensions, with which I have no experience.

Thanks again.

**Comment by bennage** [comment]
If you are are running SLAB in-process, then you can bring down the process being monitored. That's why we advise against it. Are you in a situation where you have to run in-process? Like hosting in Azure Web Apps?
If you are able to run the out-of-process service, then you can send the events to wherever you like wihtout the danger of bringing down your process. There is the [SQL sink](http://www.nuget.org/packages/EnterpriseLibrary.SemanticLogging.Database/) and others. Then it's just a matter of monitoring the storage that you are sending the events to.
Perhaps I am missing your point, though?
