### ISSUE TITLE
Semantic Logging displays incorrect Timestamp

### ISSUE THREAD

**Issue by pwalia1** [mspnp/semantic-logging#10]
There are 3 timestamps (in Red below) in each exception log message and 1 of them always seems off. We are assuming the 1st 2 timestamps are different due to GMT even though neither of them have Timezone mentioned.
To know which is the correct one, we started writing the ExceptionTime (in Green below) in the exception itself. 

Here is an example of an exception written using SemanticLogging:

![image](https://cloud.githubusercontent.com/assets/12057498/7262954/64a424c2-e832-11e4-9de3-c85d313fc80f.png)

**Comment by manikrish** [comment]
1. The default date format in slab is the "0" format which is ISO 8601 compliant. If you choose to change the format you can do so during initialization , example below: 
            listener.LogToFlatFile(@".\log.txt",new EventTextFormatter(header:null,footer:null,verbosityThreshold:EventLevel.Verbose,dateTimeFormat:"u"));
do let us know if this explains the Timestamp" property value. This does not appear to be a bug and you can customize the date format to your choice. 
2. The other issue seems to appear from a custom exception handling logger extension for the exception block and not related to the Semantic logging application block. There is an issue in the exception handling block where the TextExceptionFormatter is not customizable and you may need to write your own TextExceptionFormatter or update the code to fix it. At present we do not have any plans to make fixes to Exception handling application block. The file in question is at http://ehab.codeplex.com/SourceControl/latest#source/Src/ExceptionHandling/TextExceptionFormatter.cs

**Comment by mj1856** [comment]
@manikrish - If the timestamp is UTC, it should be written with a trailing `Z` in ISO format

```json
"Timestamp": "2015-04-21T03:34:20.216103Z"
```

Without a `Z` indicates `DateTimeKind.Unspecified` is being used instead of `DateTimeKind.Utc` - which is prefered when logging.

**Comment by manikrish** [comment]
Thanks @mj1856  for pointing this out. We do log the timestamp as UTC An example of what we log by default using the text formatter and json formatter: Timestamp : 2015-07-13T19:17:15.3945052Z
@pwalia1 hope that clarifies the question with regards to the Semantic logging block. Which sink are you using?

**Comment by manikrish** [comment]
Closing this issue since the log entry is in UTC in ISO861 format.
