### ISSUE TITLE
Seeing unexpected characters in some records written to Azure Table Storage by the out-of-process service.

### ISSUE THREAD

**Issue by peanutbutterlou** [mspnp/semantic-logging#11]
Looking to gather some ideas to explain what might be going on with my ETW tracing. 

Here's a screenshot of what I see when I look at the records written by the SLAP out-of-process service to the configured "SLAB" Azure Table: 

![2015-04-27_1329](https://cloud.githubusercontent.com/assets/2053219/7353526/3a135dea-ece2-11e4-9a5b-f49592181640.png)

I am also noticing that the malformed records are extraneous, as in they aren't the correct entries. It would appear from my screenshot that duplicate records are being written for the "OnActivate_Done" and "Configure_Done", but I believe the second entries for both events are the correct ones (outlined in red in the screenshot), while the ones outlined in orange are just plain messed up. 

Any ideas for what's going on here? I can provide additional information if requested.

**Comment by manikrish** [comment]
It would be great if you can share a repro with the config file, preferably a unit test and any environment specific settings ( like the system locale). We will investigate it further.

**Comment by manikrish** [comment]
@peanutbutterlou could you share a repro with the config file?

**Comment by peanutbutterlou** [comment]
I am unable to reproduce this on my end. Closing.
