### ISSUE TITLE
Username issues in scripts

### ISSUE THREAD

**Issue by iremmats** [mspnp/semantic-logging#14]
The mountDisks.sh script requires username to be "elasticSearch". This parameter is though setable in the powershell scripts. Please include this in the documentation.

**Comment by juliusl** [comment]
Thanks for bringing this up. I will label this as a bug, and add documentation to a Known Issues and Bugs section in our README.md. 

The actual fix should be to change the username in mountDisks.sh instead of having it hardcoded to respect the top level script.

**Comment by iremmats** [comment]
Yeah thats what I did when running it. :)

One more question. Since Im a real newbie at Ruby, you got a Service Bus input plugin too?

/Mats


Från: Julius Liu <notifications@github.com<mailto:notifications@github.com>>
Svara till: mspnp/semantic-logging <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Monday 4 May 2015 18:36
Till: mspnp/semantic-logging <semantic-logging@noreply.github.com<mailto:semantic-logging@noreply.github.com>>
Kopia: Mats Iremark <mats.iremark@e-man.se<mailto:mats.iremark@e-man.se>>
Ämne: Re: [semantic-logging] Username issues in scripts (#14)


Thanks for bringing this up. I will label this as a bug, and add documentation to a Known Issues and Bugs section in our README.md.

The actual fix should be to change the username in mountDisks.sh instead of having it hardcoded to respect the top level script.

-

**Comment by juliusl** [comment]
We do have some Service Bus input plugins in the works. If there is a specific one you are looking for go ahead and make an issue and we'll get back to you as soon as we can!

**Comment by iremmats** [comment]
Just basic Logstash plugin for reading messages with JSON body and put them into ES. How far from release are you? We want this in production asap. Ill put it up as an issue.

/Mats

Från: Julius Liu <notifications@github.com<mailto:notifications@github.com>>
Svara till: mspnp/semantic-logging <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Monday 4 May 2015 18:53
Till: mspnp/semantic-logging <semantic-logging@noreply.github.com<mailto:semantic-logging@noreply.github.com>>
Kopia: Mats Iremark <mats.iremark@e-man.se<mailto:mats.iremark@e-man.se>>
Ämne: Re: [semantic-logging] Username issues in scripts (#14)


We do have some Service Bus input plugins in the works. If there is a specific one you are looking for go ahead and make an issue and we'll get back to you as soon as we can!

-
