### ISSUE TITLE
Service Bus Input Plugin

### ISSUE THREAD

**Issue by iremmats** [mspnp/semantic-logging#15]
It would really nice to also have a Logstash plugin for Azure Service Bus that let you pull log-messages from a queue or topic.

**Comment by juliusl** [comment]
So we have a Topics plugin that I will go ahead and release today. I haven't thoroughly tested it myself but I'll go ahead and share it so you can go ahead and try it out. 

We hadn't considered writing a Queue plugin yet but I'll go ahead and add it to the backlog.

**Comment by juliusl** [comment]
Change has been committed. https://github.com/mspnp/semantic-logging/commit/50bdbefda30d1451accbe7ef6b1ceba4c759f75b
