### ISSUE TITLE
How do I install Logstash Extension?

### ISSUE THREAD

**Issue by igorgatis** [mspnp/semantic-logging#16]
The page https://github.com/mspnp/semantic-logging/blob/v3/ELK/Reference.md shows a link for setting up Logstash Extension setup. However, this link seems broken: https://github.com/mspnp/semantic-logging/blob/v3/md/LogstashExtensions.md

BTW: is ELK an upcoming (officially supported) release? I can't see it through https://github.com/mspnp/semantic-logging/. I already have a ELK stack and I'd like very much to stick with it. What's your recommendation?

**Comment by juliusl** [comment]
Sorry the links were broken, I went ahead and fixed them. 

These scripts help you get your stack on Azure and we've written plugins to help you get your Diagnostics data from Azure Diagnostics into the stack itself. If you have an ELK stack up and running, that's great, have you considered hosting it on Azure? 

If you have any data in Azure Diagnostics (WAD is the other name), or any data at all stored in Azure Storage Table's or Blobs or writing any data to Azure Service Bus Topics, then I recommend checking out our Logstash plugins to help you consume them. You can use those regardless of where you are hosting your ELK stack. 

Did that answer your question?

**Comment by juliusl** [comment]
Going ahead and closing the issue. Feel free to ask more questions if you need!
