### ISSUE TITLE
Logstash azuretopic input plugin performance

### ISSUE THREAD

**Issue by iremmats** [mspnp/semantic-logging#20]
Im getting less than 5 messages per second read with the azuretopic plugin. Have you done any performance tests with this one? Any settings that could affect performance here?
Running three ES nodes in azure on ubuntu machines.

**Comment by juliusl** [comment]
Off the top of my head you can try adding more logstash machines to see if that helps your performance but we should certainly work on getting a single machine output up from 5 mps. Do you have a performance target in mind? Also how are you measuring messages per second? (So I can test if my tweaks work.)

**Comment by iremmats** [comment]
Hi,

At first I thought it was a setting with the es cluster but I did testing with input {azuretopic} and output {stdout}. Just seeing the timestamp on what got written to the console gave me the performance. If I understand it correctly the Ruby Azure Sdk Service Bus relies on HTTP for transport while .net coding uses AMPQ. I also read that HTTP is alot slower.
We are doing log4net logging to a service bus topic and want to have atleast 50 message per second. If that means 10 instances of logstash we have to do it another way. As of right now we have a cloud service running on a Small Instance and processing about 40-50 message per second.
Please let me know if there is something I can help you guys with around this subject. We have so far used your scripts to setup clusters in all of our environments and using the azure storage logstash plugin to import webjob logs.

/Mats

Från: Julius Liu <notifications@github.com<mailto:notifications@github.com>>
Svara till: mspnp/semantic-logging <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Monday 11 May 2015 20:03
Till: mspnp/semantic-logging <semantic-logging@noreply.github.com<mailto:semantic-logging@noreply.github.com>>
Kopia: Mats Iremark <mats.iremark@e-man.se<mailto:mats.iremark@e-man.se>>
Ämne: Re: [semantic-logging] Logstash azuretopic input plugin performance (#20)


Off the top of my head you can try adding more logstash machines to see if that helps your performance but we should certainly work on getting a single machine output up from 5 mps. Do you have a performance target in mind? Also how are you measuring messages per second? (So I can test if my tweaks work.)

-

**Comment by juliusl** [comment]
Ok I've been taking a look at this since yesterday. I might have some ideas on how we can optimize. But first can I get a sample of what your log output looks like?

**Comment by juliusl** [comment]
So I think I've made some progress. I've added a new input plugin for azure topics called [azuretopicthreadable.rb](https://github.com/mspnp/semantic-logging/blob/e48bf80acea3374bb0becc36004d77d027c18374/ELK/logstash-extension/inputs/azuretopicthreadable.rb). The config looks the same as the azuretopic plugin except it has a config parameter called 'threads'. You can adjust this number and basically it will control how many concurrent threads are reading from the subscription. 

I've tested it myself and from the initial round I'm seeing: 

`3000 messages @ ~1:59 mins` using 12 threads on a `Standard_A4 class VM (8 core, 14GB)` (Using our scripts, size would be ExtraLarge) so roughly `25.21 messages/second`. 

How I tested it: 
1. I seeded the topic with 3000 messages. 
2. I started the logstash agent (`/opt/logstash/bin/logstash agent --verbose -l logstash.log -f logstash.conf`) 
3. When the pipeline started, I started a physical timer. 
4. I watched the message count on the topics from the portal combined with the stdout, and when it reached 0 I stopped the timer. (If you do this in code instead and look at the first timestamp and last timestamp that will probably be more accurate.)

You can go ahead and try that plugin and see if you can tweak it further. Other things you may try is changing the read from peek_lock to read_delete, which may be faster, but I'd read up on it to see if that meets your uses.

**Comment by iremmats** [comment]
Thanks I will test this out later today. :)

/Mats Iremark

13 maj 2015 kl. 00:51 skrev Julius Liu <notifications@github.com<mailto:notifications@github.com>>:


So I think I've made some progress. I've added a new input plugin for azure topics called azuretopicthreadable.rb<https://github.com/mspnp/semantic-logging/blob/e48bf80acea3374bb0becc36004d77d027c18374/ELK/logstash-extension/inputs/azuretopicthreadable.rb>. The config looks the same as the azuretopic plugin except it has a config parameter called 'threads'. You can adjust this number and basically it will control how many concurrent threads are reading from the subscription.

I've tested it myself and from the initial round I'm seeing:

3000 messages @ ~1:59 mins using 12 threads on a Standard_A4 class VM (8 core, 14GB) (Using our scripts, size would be ExtraLarge) so roughly 25.21 messages/second.

How I tested it:
1. I seeded the topic with 3000 messages.
2. I started the logstash agent (/opt/logstash/bin/logstash agent --verbose -l logstash.log -f logstash.conf)
3. When the pipeline started, I started a physical timer.
4. I watched the message count on the topics from the portal combined with the stdout, and when it reached 0 I stopped the timer. (If you do this in code instead and look at the first timestamp and last timestamp that will probably be more accurate.)

You can go ahead and try that plugin and see if you can tweak it further. Other things you may try is changing the read from peek_lock to read_delete, which may be faster, but I'd read up on it to see if that meets your uses.

-
