### ISSUE TITLE
Logstash Error: no such file to load -- azure

### ISSUE THREAD

**Issue by oryagel** [mspnp/semantic-logging#21]
Hi,
1) I'm trying to use the Logstash plugin in order to read from Azure table.
When I try to run Logstash using the plugin I get the following error:

``` Couldn't find any input plugin named 'azurewadtable'. Are you sure this is correct? Trying to load the azurewadtable input plugin resulted in this error: no such file to load -- azure```

What did I miss?

2) I want to use this plugin to read other tables than WAD.
Possibly Azure Storage Analytics table, is there a plugin for that as well or should I make the changes myself?

Thanks

**Comment by juliusl** [comment]
So to address the first part. When you ssh into the machine can you check the directory /opt/logstash/lib/logstash/inputs/ for the file azurewadtable.rb. If it does exist it is likely installing the azure rub sdk for some reason didn't work. While you're still have ssh open try running this command: 
```
env GEM_HOME=/opt/logstash/vendor/bundle/jruby/1.9 GEM_PATH=\"\" java -jar /opt/logstash/vendor/jar/jruby-complete-1.7.11.jar -S gem install azure
```
For reference on how the plugins get installed take a look at [lines 222-243](https://github.com/mspnp/semantic-logging/blob/v3/ELK/modules/ELKLinux.psm1#L222-L243)

For the second part of your question, the only part of that plugin that makes it WAD specific is the query we use to pull in data. You can certainly adapt the existing plugin for your own uses. To do this, duplicate the script and change the query in the process method. (lines 46-59)[https://github.com/mspnp/semantic-logging/blob/v3/ELK/logstash-extension/inputs/azurewadtable.rb#L46-L59]

If you make it general purpose enough go ahead send a pull request.
