### ISSUE TITLE
we i am installing i am getting error

### ISSUE THREAD

**Issue by kkbandaru** [mspnp/semantic-logging#23]
when I am running New-SampleELKInstance.ps1, I am getting the below error.
One or more of the follwoing commands cannot be found on ENV:PATH : ssh, scp, ssh-keygen, sed.

I have configured the PATH correctly I am able to access all the commands

**Comment by juliusl** [comment]
Sorry I though I had replies to this Issue. Have you checked that 'openssl' is on the Path?
