### ISSUE TITLE
Plugin/Input for Azure Tables

### ISSUE THREAD

**Issue by remusrg** [mspnp/semantic-logging#24]
Are there plans to support other tables (user configurable) than the WADLogsTable? I have a specific need to support the [Orleans](https://github.com/dotnet/Orleans) tables (OrleansSiloMetrics, OrleansSiloStatistics). In the more general sense, if I configure logstash.conf with a storage account and a table name, can the schema of the table be reflected automatically, or at least provided in the configuration? I can help with requirements for a contribution.

**Comment by juliusl** [comment]
In short the only WAD specific part of the plugin is the column we use to format our table query. See my response to this issue for details, [issue 21](https://github.com/mspnp/semantic-logging/issues/21). To get you going you can copy the script.

Making a stand alone plugin for Azure Tables should be straightforward. Could you add to this issue what settings you would like for this plugin? I'll mark this as an enhancement.

**Comment by remusrg** [comment]
I get a permission denied when trying to copy azurewadtable.rb to azuretable.rb (cp command). Tried this in /opt/logstash/lib/logstash/inputs. Is that the correct location?

The parameters you have for azurewadtable are good enough for now, seems like we just need to remove the PreciseTimeStamp references.

**Comment by juliusl** [comment]
Copy it in your home directory instead (see ~/logstash-extension/inputs), vi/vim to edit, then sudo \cp -rf ~/logstash-extension/* /opt/logstash/lib/logstash.

I wouldn't remove the references but change it to the column name of your timestamp column. If you do want to remove it, make sure the query you are executing is correct.


On May 20, 2015, at 23:20, Remus Radu <notifications@github.com<mailto:notifications@github.com>> wrote:


I get a permission denied when trying to copy azurewadtable.rb to azuretable.rb (cp command). Tried this in /opt/logstash/lib/logstash/inputs. Is that the correct location?

The parameters you have for azurewadtable are good enough for now, seems like we just need to remove the PreciseTimeStamp references.

-

**Comment by remusrg** [comment]
That makes sense, I'll try. All tables that I need this for have a Timestamp column already, I'd say with that we already have pretty generic at that point, no?

**Comment by remusrg** [comment]
Couple questions: 
1. I modified the logstash.conf in ~/, do I need to copy that anywhere as well?
2. Either way, to I need to sudo service logstash restart?

**Comment by juliusl** [comment]
1. Yes 'sudo \cp -f logstash.conf /etc/logstash/conf.d/'
2. Yes. You can also test stuff generally if you do '/opt/logstash/bin/logstash agent --debug' (I'm working from memory so double check before trying)


On May 21, 2015, at 00:41, Remus Radu <notifications@github.com<mailto:notifications@github.com>> wrote:


Couple questions:
1. I modified the logstash.conf in ~/, do I need to copy that anywhere as well?
2. Either way, to I need to sudo service logstash restart?

-

**Comment by remusrg** [comment]
Well, 1) it's not working and 2) the debug command (/opt/logstash/lib/logstash/runner.rb --debug) throws a permission denied error :(


Date: Thu, 21 May 2015 05:35:56 -0700

**Comment by juliusl** [comment]
It should be '/opt/logstash/bin/logstash agent --verbose -l logstash.log -f logstash.conf' (assuming eexecution from the same directory as your conf file.) If you're getting access denied errors use sudo before your command. I don't know what runner.rb does.

That should tell you what part isn't working.


On May 21, 2015, at 19:01, Remus Radu <notifications@github.com<mailto:notifications@github.com>> wrote:

Well, 1) it's not working and 2) the debug command (/opt/logstash/lib/logstash/runner.rb --debug) throws a permission denied error :(


Date: Thu, 21 May 2015 05:35:56 -0700

**Comment by juliusl** [comment]
Also you'll need to change the query filter on line 48 of azurewadtable.rb. It looks like we do something special with the partition key.

**Comment by remusrg** [comment]
If this helps, here's what I find now in the logstash.log:
{:timestamp=>"2015-05-21T16:52:43.366000+0000", :message=>"Using milestone 0 input plugin 'azurewadtable'. This plugin isn't well supported by the community and likely has no maintainer. For more information on plugin milestones, see http://logstash.net/docs/1.4.2-modified/plugin-milestones", :level=>:warn}{:timestamp=>"2015-05-21T16:52:44.057000+0000", :message=>"+---------------------------------------------------------+\n| An unexpected error occurred. This is probably a bug.   |\n| You can find help with this problem in a few places:    |\n|                                                         |\n| * chat: #logstash IRC channel on freenode irc.          |\n|     IRC via the web: http://goo.gl/TI4Ro                |\n| * email: logstash-users@googlegroups.com                |\n| * bug system: https://logstash.jira.com/                |\n|                                                         |\n+---------------------------------------------------------+\nThe error reported is: \n  nil is not a string"}

At the moment I am not getting any data through anymore so I must have broken something. I'll try your suggestion next.

Date: Thu, 21 May 2015 12:21:40 -0700

**Comment by remusrg** [comment]
/opt/logstash/lib/logstash/inputs/azuretable.rb:19 warning: already initialized constant TICKS_SINCE_EPOCH
+---------------------------------------------------------+
| An unexpected error occurred. This is probably a bug.   |
| You can find help with this problem in a few places:    |
|                                                         |
| * chat: #logstash IRC channel on freenode irc.          |
|     IRC via the web: http://goo.gl/TI4Ro                |
| * email: logstash-users@googlegroups.com                |
| * bug system: https://logstash.jira.com/                |
|                                                         |
+---------------------------------------------------------+
The error reported is:
  nil is not a string
etg@elk-sample:~$

**Comment by remusrg** [comment]
Forgot to change the class name, trying again...

**Comment by remusrg** [comment]
That worked well, getting data through via the new input. Should I make a pull request?

**Comment by juliusl** [comment]
Sure!

**Comment by juliusl** [comment]
Hey Remus, Did you ever get a chance to set up that pull request? Sorry for the delay I've just come back from holiday.
