### ISSUE TITLE
TraceEventServiceFixture test consistently failing

### ISSUE THREAD

**Issue by richardszalay** [mspnp/semantic-logging#30]
The test:

```
given_traceEventService
when_logging_multiple_events_from_a_process_process_with_sampling
then_sampled_events_are_collected_and_processed
```

Is currently failing with no events being captured (`EVENT_SOURCE_PACKAGE` is _not_ defined in the build).

Is this a known issue?

**Comment by bennage** [comment]
Please see the note on #91. We are no longer working on Semantic Logging.
