### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by Expecho** [mspnp/semantic-logging#32]
Hi Guys, what are the plans for vNext of the semantic logging block. Do you plan to support more out-of-the box sinks like EventHub or DocumentDB? Can you share some plans for the future? There's not a lot activity around the semantic logging block when it comes to future plans.. Or is there another place I should look for to find this kind of information?

**Comment by mabsimms** [comment]
We're currently working through aligning the future of structured logging guidance with some of the ongoing enhancements in ASP.NET and .NET v.Next.  No details to share as of yet; when we have something concrete it will show up here first (and yes, more OOB connectivity and e2e scenarios are definitely top of mind)

**Comment by RichiCoder1** [comment]
*bump*

**Comment by bennage** [comment]
We just posted a [preliminary roadmap](#91).
