### ISSUE TITLE
EnterpriseLibrary.SemanticLogging.EventSourceAnalyzer for .net4.6

### ISSUE THREAD

**Issue by innovate-data** [mspnp/semantic-logging#33]
Is there a version of EnterpriseLibrary.SemanticLogging.EventSourceAnalyzer targetted for .net 4.6 ?
or will the existing version="2.0.1406.1" work for .net 4.6 as well ?

I am using the EventSourceAnalyzer.InspectAll(MyEventSource) which works fine in .net 4.5.2 framework , but throws the following exception when tested against .net 4.6

"Microsoft.Practices.EnterpriseLibrary.SemanticLogging.Utility.EventSourceAnalyzerException: The specified EventSource does not have any method decorated with EventAttribute."

I am using the following two packages
<package id="EnterpriseLibrary.SemanticLogging" version="2.0.1406.1" targetFramework="net452" />
<package id="EnterpriseLibrary.SemanticLogging.EventSourceAnalyzer" version="2.0.1406.1" targetFramework="net452" />

Any help is appreciated

**Comment by mekoda** [comment]
Hi @innovate-data, could you provide us a repro project where this issue can be reproduced? I did a quick test and SemanticLogging seems to work well with .NET 4.6.

**Comment by mekoda** [comment]
Closing it due to lack of inactivity.
