### ISSUE TITLE
Missing support for custom stored procedure name in SqlServer sink / Writing to different tables

### ISSUE THREAD

**Issue by Expecho** [mspnp/semantic-logging#34]
I want to write different eventsources to different tables. I assume that the tableName parameter is intended for that scenario but the stored procedure that is used cannot be set from code. How is this supposed to work or is this scenario not supported? How about making the stored procedure name settable like the table name, that would make it easy to support this scenario.

**Comment by mekoda** [comment]
Hello @Expecho, you are right. The *tableName* parameter is meant to be used when targeting different tables, and the store procedure name can be settable to support this new scenario. Could you make a pull request with the proposed fix?

Meanwhile, you can achieve writing to different tables using different databases.

**Comment by Expecho** [comment]
Hi @mekoda, I created a pull request with the proposed fix. See request https://github.com/mspnp/semantic-logging/pull/36
