### ISSUE TITLE
Common buffering approach in all sinks to deal with internal sink failures

### ISSUE THREAD

**Issue by manikrish** [mspnp/semantic-logging#35]
Currently the remote sinks ( SQL and Azure Table) make use of a buffering mechanism which drops messages when they hit an upperbound number. 
The built in sinks in async mode ( Flat file and Rolling flat file) make use of a different buffering mechanism which does not set an upperbound.
1. Follow same approach across all sinks.
2. Investigate adding a setting to buffering mechanism in all sinks where we buffer by size in addition to count. 
3. Investigate simplifying the buffering implementation to make use of the Task Parallel Library instead of using a concurrent collection.

**Comment by bennage** [comment]
Please see the note on #91. We are no longer working on Semantic Logging.
