### ISSUE TITLE
Logstash azurewadtable plugin returning 400 One of the request inputs is not valid

### ISSUE THREAD

**Issue by bkaid** [mspnp/semantic-logging#37]
I have a cloud service configured to save off custom ETW logs with Azure Diagnostics.  I can browse the table fine with table explorer and it has data in it. When trying to consume the table with the azurewadtable plugin, I get:  `Oh My, An error occurred. {:exception=>#<Azure::Core::Http::HTTPError: InvalidInput (400): One of the request inputs is not valid.`  I verified these tables do have PreciseTimeStamp fields and have verified the account name/key.
![table](https://cloud.githubusercontent.com/assets/315615/9526194/aaec57dc-4c9c-11e5-9aa5-70c0c8521229.png)

Whats the best way to troubleshoot this?

Full debug output / stacktrace:

←[36mReading config file {:file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/agent.rb", :level=>:debug, :line=>"309", :method=>"local_config"}←[0m
←[36mCompiled pipeline code:
        @inputs = []
        @filters = []
        @outputs = []
        @periodic_flushers = []
        @shutdown_flushers = []

          @input_azurewadtable_1 = plugin("input", "azurewadtable", LogStash::Util.hash_merge_many({ "account_name" => ("my_account_name") }, { "access_key" => ("my_account_key") }, { "table_name" => ("WADReceivedMessageTable") }))

          @inputs << @input_azurewadtable_1

  def filter_func(event)
    events = [event]
    @logger.debug? && @logger.debug("filter received", :event => event.to_hash)
    events
  end
  def output_func(event)
    @logger.debug? && @logger.debug("output received", :event => event.to_hash)
  end {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb", :line=>"29", :method=>"initialize"}←[0m
←[36mPlugin not defined in namespace, checking for plugin file {:type=>"input", :name=>"azurewadtable", :path=>"logstash/inputs/azurewadtable", :level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/plugin.rb", :line=>"133", :method=>"lookup"}←[0m
←[33mazurewadtable plugin is using the 'milestone' method to declare the version of the plugin this method is deprecated in favor of declaring the version inside the gemspec. {:level=>:warn, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/config/mixin.rb", :line=>"139", :method=>"milestone"}←[0m
←[32mUsing version 0.9.x input plugin 'azurewadtable'. This plugin should work but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin. {:level=>:info, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/config/mixin.rb", :line=>"227", :method=>"print_version_notice"}←[0m
←[36mPlugin not defined in namespace, checking for plugin file {:type=>"codec", :name=>"plain", :path=>"logstash/codecs/plain", :level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/plugin.rb", :line=>"133", :method=>"lookup"}←[0m
←[36mconfig LogStash::Codecs::Plain/@charset = "UTF-8" {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/config/mixin.rb", :line=>"111", :method=>"config_init"}←[0m
←[36mconfig LogStash::Inputs::AzureWADTable/@account_name = "my_account_name" {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/config/mixin.rb", :line=>"111", :method=>"config_init"}←[0m
←[36mconfig LogStash::Inputs::AzureWADTable/@access_key = "my_account_key" {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/config/mixin.rb", :line=>"111", :method=>"config_init"}←[0m
←[36mconfig LogStash::Inputs::AzureWADTable/@table_name = "WADReceivedMessageTable" {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/config/mixin.rb", :line=>"111", :method=>"config_init"}←[0m
←[36mconfig LogStash::Inputs::AzureWADTable/@debug = false {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/config/mixin.rb", :line=>"111", :method=>"config_init"}←[0m
←[36mconfig LogStash::Inputs::AzureWADTable/@codec = <LogStash::Codecs::Plain charset=>"UTF-8"> {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/config/mixin.rb", :line=>"111", :method=>"config_init"}←[0m
←[36mconfig LogStash::Inputs::AzureWADTable/@add_field = {} {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/config/mixin.rb", :line=>"111", :method=>"config_init"}←[0m
←[36mconfig LogStash::Inputs::AzureWADTable/@entity_count_to_process = 100 {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/config/mixin.rb", :line=>"111", :method=>"config_init"}←[0m
←[36mconfig LogStash::Inputs::AzureWADTable/@collection_start_time_utc = "2015-08-27 15:53:36 UTC" {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/config/mixin.rb", :line=>"111", :method=>"config_init"}←[0m
←[36mconfig LogStash::Inputs::AzureWADTable/@etw_pretty_print = false {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/config/mixin.rb", :line=>"111", :method=>"config_init"}←[0m
←[36mconfig LogStash::Inputs::AzureWADTable/@idle_delay_seconds = 15 {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/config/mixin.rb", :line=>"111", :method=>"config_init"}←[0m
←[36mStarting process method @2015-08-27 08:53:36 -0700 {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azurewadtable-0.9.2/lib/logstash/inputs/azurewadtable.rb", :line=>"41", :method=>"run"}←[0m
←[32mPipeline started {:level=>:info, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb", :line=>"87", :method=>"run"}←[0m
←[36m2015-08-27 15:53:36 UTC {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azurewadtable-0.9.2/lib/logstash/inputs/azurewadtable.rb", :line=>"53", :method=>"process"}←[0m
←[36mcollection time parsed successfully 2015-08-27 15:53:36 UTC {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azurewadtable-0.9.2/lib/logstash/inputs/azurewadtable.rb", :line=>"109", :method=>"partitionkey_from_datetime"}←[0m
Logstash startup completed
←[36mConverting time to ticks {:level=>:debug, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azurewadtable-0.9.2/lib/logstash/inputs/azurewadtable.rb", :line=>"121", :method=>"to_ticks"}←[0m
←[31mOh My, An error occurred. {:exception=>#<Azure::Core::Http::HTTPError: InvalidInput (400): One of the request inputs is not valid.
RequestId:ab95e112-0002-006f-1ce0-e033e2000000
Time:2015-08-27T15:53:42.3490985Z>, :level=>:error, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azurewadtable-0.9.2/lib/logstash/inputs/azurewadtable.rb", :line=>"98", :method=>"process"}←[0m
←[31mA plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::AzureWADTable account_name=>"my_account_name", access_key=>"my_account_key", table_name=>"WADReceivedMessageTable", debug=>false, codec=><LogStash::Codecs::Plain charset=>"UTF-8">, entity_count_to_process=>100, collection_start_time_utc=>"2015-08-27 15:53:36 UTC", etw_pretty_print=>false, idle_delay_seconds=>15>
  Error: InvalidInput (400): One of the request inputs is not valid.
RequestId:ab95e112-0002-006f-1ce0-e033e2000000
Time:2015-08-27T15:53:42.3490985Z
  Exception: Azure::Core::Http::HTTPError
  Stack: c:/elk/logstash/vendor/bundle/jruby/1.9/gems/azure-0.6.4/lib/azure/core/http/http_request.rb:151:in `call'
org/jruby/RubyMethod.java:116:in `call'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/azure-0.6.4/lib/azure/core/http/signer_filter.rb:29:in `call'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/azure-0.6.4/lib/azure/core/http/http_request.rb:84:in `call'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/azure-0.6.4/lib/azure/core/service.rb:47:in `call'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/azure-0.6.4/lib/azure/core/filtered_service.rb:33:in `call'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/azure-0.6.4/lib/azure/core/signed_service.rb:39:in `call'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/azure-0.6.4/lib/azure/table/table_service.rb:252:in `query_entities'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azurewadtable-0.9.2/lib/logstash/inputs/azurewadtable.rb:57:in `process'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azurewadtable-0.9.2/lib/logstash/inputs/azurewadtable.rb:42:in `run'
org/jruby/RubyKernel.java:1511:in `loop'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azurewadtable-0.9.2/lib/logstash/inputs/azurewadtable.rb:40:in `run'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:177:in `inputworker'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:171:in `start_input' {:level=>:error, :file=>"/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb", :line=>"182", :method=>"inputworker"}←[0m
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/azure-0.6.4/lib/azure/core/http/http_request.rb:151:in `call'
org/jruby/RubyMethod.java:116:in `call'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/azure-0.6.4/lib/azure/core/http/signer_filter.rb:29:in `call'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/azure-0.6.4/lib/azure/core/http/http_request.rb:84:in `call'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/azure-0.6.4/lib/azure/core/service.rb:47:in `call'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/azure-0.6.4/lib/azure/core/filtered_service.rb:33:in `call'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/azure-0.6.4/lib/azure/core/signed_service.rb:39:in `call'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/azure-0.6.4/lib/azure/table/table_service.rb:252:in `query_entities'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azurewadtable-0.9.2/lib/logstash/inputs/azurewadtable.rb:57:in `process'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azurewadtable-0.9.2/lib/logstash/inputs/azurewadtable.rb:42:in `run'
org/jruby/RubyKernel.java:1511:in `loop'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azurewadtable-0.9.2/lib/logstash/inputs/azurewadtable.rb:40:in `run'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:177:in `inputworker'
c:/elk/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:171:in `start_input'

**Comment by juliusl** [comment]
Could I see the logstash.conf (sans account name/ access key)?

**Comment by bkaid** [comment]
Here is my .conf file:

    input { 
      azurewadtable {
        account_name => "my_account_name"
        access_key => "my_account_key"
        table_name => "WADReceivedMessageTable"
      }
    }

**Comment by bkaid** [comment]
I used the httplog ruby gem to capture the HTTP requests:

E, [2015-08-27T10:08:14.305000 #7576] ERROR -- : [httplog] Connecting: my_account_name.table.core.windows.net:80
E, [2015-08-27T10:08:14.360000 #7576] ERROR -- : [httplog] Sending: GET http://my_account_name.table.core.windows.net:80/WADReceivedMessageTable()?$filter=PartitionKey+gt+%270635762920800000000%27+and+PreciseTimeStamp+gt+datetime%272015-08-27+17%3A08%3A09+UTC%27&$top=100
E, [2015-08-27T10:08:14.361000 #7576] ERROR -- : [httplog] Data:
E, [2015-08-27T10:08:14.438000 #7576] ERROR -- : [httplog] Status: 400
E, [2015-08-27T10:08:14.439000 #7576] ERROR -- : [httplog] Benchmark: 0.076 seconds
E, [2015-08-27T10:08:14.439000 #7576] ERROR -- : [httplog] Response:
<?xml version="1.0" encoding="utf-8"?><error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><code>InvalidInput</zcode><message xml:lang="en-US">One of the request inputs is not valid.
RequestId:bd84eb81-0002-0012-17ea-e0af2a000000
Time:2015-08-27T17:08:14.5983101Z</message></error>

**Comment by juliusl** [comment]
Thanks, I was just about to ask for that. I'll take a look.

**Comment by juliusl** [comment]
Could you add this line to your logstash.conf:
`
collection_start_time_utc => "2015-04-01T23:57:27.307Z"
`
and try running it again?

**Comment by bkaid** [comment]
Based on the httplog info, it looks like the filter it is sending is `PartitionKey gt '0635762920800000000' and PreciseTimeStamp gt datetime'2015-08-27 17:08:09 UTC'` and if I use that same query in Visual Studio I also get an error:  
![table-filter](https://cloud.githubusercontent.com/assets/315615/9527694/70913b8a-4ca5-11e5-9de1-520ca82498c1.png)

**Comment by juliusl** [comment]
Yeah I think its the datetime format of the PreciseTimeStamp part. 

I suspect it needs to be ISO-8061. Change the query to 
` and PreciseTimeStamp gt datetime'2015-04-01T23:57:27.307Z' `

and see what happens.

**Comment by bkaid** [comment]
Switching to ISO-8061 format in Visual Studio works:
![table-filter-iso](https://cloud.githubusercontent.com/assets/315615/9527903/aa3aaa00-4ca6-11e5-8117-f9582ac465d5.png)

When I added the `collection_start_time_utc` item to the .conf file as requested it did start spitting out all the messages to the console but it was hard to tell if there were any errors as the messages were so long.

**Comment by juliusl** [comment]
Yeah it looks like a bug on our side using Time.now.utc.inspect. 

I'll fix it, but for now if you set the collection_start_time_utc in the way above it should solve your problem.

**Comment by bkaid** [comment]
Thanks for your help - I also got it working by updating the code: from `Time.now.utc.inspect` to `Time.now.utc.iso8601`

**Comment by juliusl** [comment]
No problem! I've committed the fix :)

**Comment by bkaid** [comment]
It crashes again once it actually data.  This line also needs the same ISO 8601 fix:
`@last_timestamp = result.last.properties["PreciseTimeStamp"].inspect`

**Comment by juliusl** [comment]
Nice catch! I updated the plugin. 

I think Azure might've changed something server side since this used to work fine.
