### ISSUE TITLE
Cant self host out-of-proc sinks

### ISSUE THREAD

**Issue by negativeeddy** [mspnp/semantic-logging#38]
I want to self host instead of installing the existing windows service project. That way I can incorporate it into an existing service I already have.

I've found two issues preventing this
1) certain classes need to be made public instead of internal
2) the EventSource I'm using (from a windows 8 project) doesn't work if the session is enabled with the default arguments

**Comment by mekoda** [comment]
Hello @negativeeddy, 

I see this as a feature rather than an issue; moreover, it can be a great contribution to the community.

Feel free to clone the repo and modify the code in order to achieve this. Then, you can support the project by creating a pull request with your contribution.
