### ISSUE TITLE
Oracle support

### ISSUE THREAD

**Issue by vladek47** [mspnp/semantic-logging#4]
Hi,
I’m in a need for Oracle sink and I was thinking for implementing it myself using MS SQL Server sink as a starting point unless there are official plans for adding Oracle support to SLAB. Are there any plans for that? If there aren't any plans and I implement my own sink I was wandering if you'll consider Oracle sink for pull request?
Best regards

**Comment by bennage** [comment]
We do not have plans for an Oracle sink. If you do implement one, please let us know and we'll link to.
