### ISSUE TITLE
Subscribing to events from Microsoft-SemanticLogging itself

### ISSUE THREAD

**Issue by potomato** [mspnp/semantic-logging#40]
I would like to have a custom sink in the standard out-of-process host which is listening to events from SemanticLoggingEventSource (i.e. itself - name = "Microsoft-SemanticLogging"). This is so I can fire off an email in case of 806/807 messages. By default the out-of-process app logs to EventLog or Console. 
I can configure a sink to listen on this source name, but it doesn't get notified about these internal events.
If I start another SemanticLogging-svc.exe instance configured to listen on "Microsoft-SemanticLogging" first, then it is notified about 806/807 etc events fired from the main SemanticLogging-svc.exe instance when they are seen in the console there. However I need to start the instances in the correct order, and I don't want to have 2 instances running anyway.

Is there any way to call a custom sink inside the standard out-of-process host when the SemanticLoggingEventSource writes events?

**Comment by potomato** [comment]
This is working for me now.

**Comment by potomato** [comment]
This was briefly working for me but has reverted to prior behaviour, where a sink listen to "Microsoft-SemanticLogging" does not receive events.

**Comment by mekoda** [comment]
Hi @potomato, sorry for the delay.

The Semantic Logging Application Block is able to listen to any ETW events (it doesn't matter the origin), including all the events that it triggers.

You can set up a custom sink like this:

``` 
<customSink name="CounterSink"  type ="CounterSink.CounterSink, CounterSink">
  <sources>
    <eventSource name="Microsoft-SemanticLogging"  level="LogAlways" />
  </sources>
</customSink>
```

With this approach you will get all the events triggered by SLAB in the ```OnNext(EventEntry value)``` method. You can get more information about how to define custom sinks in [this link](https://msdn.microsoft.com/en-us/library/dn775003(v=pandp.20).aspx).

Regarding the events you are not receiving: Are these events actually being triggered? You can check this using [Perfview](https://blogs.msdn.microsoft.com/vancem/2012/07/09/introduction-tutorial-logging-etw-events-in-c-system-diagnostics-tracing-eventsource/).
