### ISSUE TITLE
EventSourceAnalyzer can't inspect Microsoft.Diagnostics.Tracing.EventSource

### ISSUE THREAD

**Issue by kelmen** [mspnp/semantic-logging#41]
trying to use EventSourceAnalyzer to validate my custom EventSource, which is derived from Microsoft.Diagnostics.Tracing.EventSource

not allow, getting compile error "Cannot convert type ??? via a reference conversion ..."

the reason I adopting Microsoft.Diagnostics.Tracing.EventSource, because there is a tool (Microsoft.Diagnostics.Tracing.RegisterEvent) to generate etw manifest file.

**Comment by mekoda** [comment]
Hi @kelmen,

I think the discussion regarding issue #27 can help. If not, please let me know.
