### ISSUE TITLE
Minimalist ELK setup from the doc keeps failing

### ISSUE THREAD

**Issue by dhrumil83** [mspnp/semantic-logging#43]
Here is error.

9/15/2015 6:15:58 PM - [Configuration] Installing ElasticSearch.Exception calling "Invoke" with "1" argument(s): "Exec:
Failed to run ssh -o ConnectTimeout=360 -o
StrictHostKeychecking=no -o UserKnownHostsFile=NUL -i id_rsa -p $SshPort $SshString  $UpdateCommand"
At C:\LogProject\semantic-logging-elk\semantic-logging-elk\ELK\modules\deployment.psm1:50 char:3
+   $setupFunction.Invoke($VMName)
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : RuntimeException

**Comment by mekoda** [comment]
Hello @dhrumil83,

Can you provide a repro project for this? Thanks.

**Comment by ctaggart** [comment]
Do you have a link to the docs?

Also, is it true that the out of process service doesn't work with ElasticSearch? http://stackoverflow.com/a/28638873/23059
