### ISSUE TITLE
No support for "dynamic" events introduced in .Net Framework 4.6

### ISSUE THREAD

**Issue by spacewrangler** [mspnp/semantic-logging#44]
.Net Framework 4.6 introduced the concept of "dynamic" events via the Write<T>(String, T) method (and similar overloads). These are super handy as I can create events dynamically without declaring the events up front. It's a great way for me to build flexible logging that allows for variable payloads.

These dynamic events don't work with semantic logging because there is no event ID associated with them, they just have a name. Well, technically there is an ID but it's -1. So from an SL perspective, these events don't really exist on the EventSource. Consequently, SL fails to lookup the schema and then fails to create the EventEntry is passes to the observers.

The following console app reproduces the issue (must target Framework 4.6 to build & run). When you run this you should get a 1st-chance exception (that gets swallowed and logged by SL) in `EventSourceSchemaCache.GetSchema(...)`

``` C#
using System;
using System.Diagnostics.Tracing;
using Microsoft.Practices.EnterpriseLibrary.SemanticLogging;

namespace Net46Test
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Let's write some logs!");

            var myLogger = new EventSource("MyComponentLogger");
            var slabListener = new ObservableEventListener();
            slabListener.EnableEvents(myLogger, EventLevel.LogAlways);
            slabListener.LogToConsole();

            // Something bad happens

            var myEvent = new MyDiagEvent { Message = "Something bad happened" };
            myLogger.Write<MyDiagEvent>("MyDiagEvent", myEvent);

            Console.ReadLine();
        }
    }

    [EventData()]
    public class MyDiagEvent
    {
        public string Message { get; set; }
    }
}
```

I _think_ we need to add support for the "self describing event format" events. (There are some notes on this in the EventSource source at https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs.) 
Any chance this is on your radar for a future release?

**Comment by leisurelyclouds** [comment]
"dynamic" events called "[TraceLogging](https://msdn.microsoft.com/en-us/library/dn904628(v=vs.85).aspx)"

the reason is
for dynamic events
SemanticLogging->Schema->EventSourceSchemaCache.cs->
`return events[eventId];` 
eventId should be 0
but parameter "eventId" is -1。

replace with 
```
if (events.ContainsKey(eventId))
{
    return events[eventId];
}
return events[0];
```
can working but not perfect.

**Comment by cwe1ss** [comment]
any update on this? I also think this would be an important feature.

**Comment by neuecc** [comment]
Hi,
Unfortunately SLAB is not updated...
I've made alternative of EventSource based logging library.
https://github.com/neuecc/EtwStream
It works well.

**Comment by mekoda** [comment]
Hi everyone, 

We are currently discussing about this, more information will be shared soon in issue #64 .

**Comment by bennage** [comment]
Please see the note on #91. We are no longer working on Semantic Logging.
