### ISSUE TITLE
Support for custom fields within the SqlSink tables

### ISSUE THREAD

**Issue by davea38** [mspnp/semantic-logging#46]
Is there any way of adding custom fields to the SQLSink table. I want to have an audit table structure like:

        [id] [bigint] IDENTITY(1,1) NOT NULL,
        __**[CustomField1] [nvarchar](10]**__,
        __**[CustomField2] [nvarchar](10]**__,
	[InstanceName] [nvarchar](1000) NOT NULL,
	[ProviderId] [uniqueidentifier] NOT NULL,
	[ProviderName] [nvarchar](500) NOT NULL,
	[EventId] [int] NOT NULL,
	[EventKeywords] [bigint] NOT NULL,
	[Level] [int] NOT NULL,
	[Opcode] [int] NOT NULL,
	[Task] [int] NOT NULL,
	[Timestamp] [datetimeoffset](7) NOT NULL,
	[Version] [int] NOT NULL,
	[FormattedMessage] [nvarchar](4000) NULL,
	[Payload] [nvarchar](4000) NULL,
	[ActivityId] [uniqueidentifier],
	[RelatedActivityId] [uniqueidentifier],
	[ProcessId] [int],
	[ThreadId] [int]

I presume that I would need to amend the TracesType custom database type to add my two custom fields, but can I write a custom event sink to construct the TracesType object?

**Comment by Expecho** [comment]
Why can't you put those fields in the payload?

Anyway, there are currently two ways data is inserted into the table. Using a stored procedure (which uses the custom database type) or using the sqlbulkcopy copy that inserts the data directly.

You will have to create your own database sink in order to support the above scenario. You can take a look at https://github.com/DeHeerSoftware/SemanticLogging.Database.Xml for an example on how to do this.

**Comment by davea38** [comment]
The fields could absolutely go in the payload, however in my solution the logging database will be a seperate entity that will contain more than just system audit information. It's dramatically easier for future developers to have the information split out - SQL doesn't deal with querying JSON as of this moment, kind of makes storing logging information in database format a bit less useful!

In my case, it will be two primary key value fields that exist in another database. Thanks for pointing out the XML fork - its a sensible solution that makes the payload potentially usable!

I'll probably use that in conjunction with my own database sink and modify the SQL structure (table / custom database type) to accomodate this.

This project doesn't seem very active at the moment so there's not much chance of needing to upgrade and accidentally overwrite the customisations.

Thanks for your response :)

**Comment by Expecho** [comment]
You're welcome. Note that the repository I pointed to is not a fork but rather a custom sink assembly. This minimizes the risk that you have to manually merge changes when the official project is updated.

**Comment by davea38** [comment]
Ahhh! That's even better! Thank you very much for your help - much appreciated :)
