### ISSUE TITLE
Mismatched Event IDs in SemanticLoggingEventSource 

### ISSUE THREAD

**Issue by jeffreywstevens** [mspnp/semantic-logging#53]
WriteEvent should have id of 1000 to match.  I founded this by running all of the unit tests in the source solution.  The error message was more cryptic.  13 failed tests on my machine.  33 skipped test.

        [Event(1000, Level = EventLevel.Error, Keywords = Keywords.Sink, Message = "Parsing the manifest for provider '{0}' to handle the event with ID {1} failed. Message: {2}")]
        internal void ParsingEventSourceManifestFailed(string providerName, int eventId, string message)
        {
            if (this.IsEnabled())
            {
                this.WriteEvent(903, providerName, eventId, message);
            }
        }

**Comment by mekoda** [comment]
Thanks @jeffreywstevens! We will take a look.

**Comment by mekoda** [comment]
This is now solved in PR #62 . Thanks again @jeffreywstevens !
