### ISSUE TITLE
EventSourceException when using SLAB out-of-process with 4.6 runtime

### ISSUE THREAD

**Issue by Unrefraction** [mspnp/semantic-logging#54]
On our project we are using SLAB out-of-process service with Azure Table Storage. 
EnterpriseLibrary.SemanticLogging.Service.2.0.1406.1

After updating runtime to 4.6 every time when new log is written by calling WriteEventWithRelatedActivityId, an additional record appears in azure table with the next payload

```
{
  "message": "EventSourceException"
}
```

This error doesn't appear if WriteEvent is called. 

Tried to reproduce on another machine with 4.5 runtime installed - no exception message.

**Comment by mekoda** [comment]
Hi @Unrefraction,

We are currently discussing about 4.6 support, more information will be shared soon in issue #64 .

**Comment by bennage** [comment]
Please see the note on #91. We are no longer working on Semantic Logging.
