### ISSUE TITLE
COMException during initialization

### ISSUE THREAD

**Issue by aelij** [mspnp/semantic-logging#61]
I'm getting the following exception after calling `TraceEventService.Start`. It seems that the `sendManifest` parameter in `EnableProvider` is the problem; the exception occurs when it's set to `true`.

I'm actually using SLAB now with this flag always set to `false`, so I'm not sure why this is needed at all.

My .NET Framework version is 4.6.1.

```
System.Runtime.InteropServices.COMException (0x80071068): The GUID passed was not recognized as valid by a WMI data provider. (Exception from HRESULT: 0x80071068)
  at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
  at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
  at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableProvider(Guid providerGuid, TraceEventLevel providerLevel, UInt64 matchAnyKeywords, TraceEventProviderOptions options)
```

**Comment by mekoda** [comment]
Hi @aelij, thanks for the contribution.

Could you share a repro project so I can take a closer look to this?

**Comment by aelij** [comment]
Here's the repro. If you comment out the Command, there's no exception. I've tried this (using SLAB, not this minimal repro) on several machines, including a few Azure VMs (all have .NET 4.6.1 installed) with the same result.

```csharp
using (var session = new TraceEventSession("MySession", null) { StopOnDispose = true })
{
    var guid = TraceEventProviders.GetEventSourceGuidFromName("MyProvider");
    var traceEventProviderOptions = new TraceEventProviderOptions
    {
        Arguments = new Dictionary<string, string>
        {
            ["Command"] = "SendManifest"
        },
        ProcessNameFilter = new string[0]
    };
    session.EnableProvider(guid, TraceEventLevel.Informational, options: traceEventProviderOptions);
}
```

Thanks!

**Comment by mekoda** [comment]
I think there are two things to consider in this scenario:

- 1. Did you recompile SLAB to use it with the newer ```EventSource``` (from the Microsoft namespace)? You will need to do it in order to use it with it instead of the one from the System namespace. You can reach more details in #27.
- 2. (and most important) We are currently discussing about the .NET 4.6 support. You will find the conclusions in #64 .

**Comment by aelij** [comment]
Hi,

1. No, why should I do that? We're using the .NET 4.6.1 EventSource class to write events. 
2. Thanks. I think that may cause the issue I described. 

Do you know how come SLAB works fine even without the SendManifest command?

Thanks.

**Comment by bennage** [comment]
Please see the note on #91. We are no longer working on Semantic Logging.
