### ISSUE TITLE
EventSourceAnalyzer.InspectAll does not work with Microsoft.Diagnostics.Tracing.EventSource

### ISSUE THREAD

**Issue by dfch** [mspnp/semantic-logging#63]
Hi, I have an issue with `EventSourceAnalyzer.InspectAll()` after installing the [Microsoft EventSource Library 1.1.28](https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventSource).

# Description
I used `Microsoft.Diagnostics.Tracing.EventSource` from the .NET framework before and I created an event source class and everything worked just fine:

``` csharp
public class MyEventSource : Microsoft.Diagnostics.Tracing.EventSource()
{
  // ...
}
```

In my test project I created the following test to verify the correctness of the class:

``` csharp
  [TestClass]
  public class MyEventSourceTest
  {
    [TestMethod]
    public void InspectAllShouldSuccedOrWeHaveNoLogging()
    {
      EventSourceAnalyzer.InspectAll(MyEventSource.Default);
    }
  }
```

From the the signature of `InspectAll` I can clearly see that it only supports the *internal* `System.Diagnostics.Tracing.EventSource` class:

``` csharp
public static void InspectAll(System.Diagnostics.Tracing.EventSource eventSource);
```

# Question
I actually updated to the newest `EventSource` library as I read about some of its improvements compared to the *internal* version.

* However, I am wondering why the `InspectAll` method does not support this `EventSource`? 
* What I am I doing wrong? 
* Is this an intended behaviour?
* How am I supposed to *inspect* a custom event source? Is there another way how I can achieve this?

Thanks for your feedback an reply!

Below you find the installed package versions (in an abbreviated form) for the main and the test project.

# Notes

This issue somehow relates to the following issues (but I created a new issue as it does not totally fit the existing ones):

* #41 (this is actually pretty much the problem I described, however the issue was reredirected to the issues below)
* #27
* #33

# Packages in main project
``` posh
PM> get-package | Select Id, Version | ft -autosize

Id                                                    Version        
--                                                    -------        
EnterpriseLibrary.SemanticLogging                     2.0.1406.1     
EnterpriseLibrary.SemanticLogging.EventSourceAnalyzer 2.0.1406.1     
Microsoft.Diagnostics.Tracing.EventRegister           1.1.28         
Microsoft.Diagnostics.Tracing.EventSource             1.1.28         
Microsoft.Diagnostics.Tracing.EventSource.Redist      1.1.28         
```

# Packages in test project

``` posh
PM> get-package -ProjectName TestProject | Select Id, Version | ft -autosize

Id                                                    Version        
--                                                    -------        
EnterpriseLibrary.SemanticLogging                     2.0.1406.1     
EnterpriseLibrary.SemanticLogging.EventSourceAnalyzer 2.0.1406.1     
EntityFramework                                       6.1.3          
Microsoft.Diagnostics.Tracing.EventRegister           1.1.28         
Microsoft.Diagnostics.Tracing.EventSource             1.1.28         
Microsoft.Diagnostics.Tracing.EventSource.Redist      1.1.28         
Microsoft.WindowsAzure.ConfigurationManager           2.0.0.0        
```

**Comment by mekoda** [comment]
Hi @dfch, thanks for the details, which are really useful to understand the scenario.

At a glance: in order to support `Microsoft.Diagnostics.Tracing.EventSource` you have to modify the code and recompile the solution.

> However, I am wondering why the InspectAll method does not support this EventSource?

`System.Diagnostics.Tracing.EventSource` comes by default with the .NET Framework, and it was the only EventSource at first; this is why it has been chosen as the first guess. 

> What I am I doing wrong?
> Is this an intended behaviour?

Usually, Semantic Logging is used with `System.Diagnostics.Tracing.EventSource`. However, you can modify and recompile the solution referencing the other EventSource, this will allow you to use it.

> How am I supposed to inspect a custom event source? Is there another way how I can achieve this?

In #27 you will find the details to use the EventSource from the Microsoft namespace, this is the way to achieve what you are looking for.
