### ISSUE TITLE
.NET 4.6 support 

### ISSUE THREAD

**Issue by mekoda** [mspnp/semantic-logging#64]
Hi everyone, 

We are currently discussing about this topic. Stay tuned here, we will share more information soon.

**Comment by cwe1ss** [comment]
...waiting... :) would be great to have 4.6 support as soon as possible. I'd be willing to help!

**Comment by Ed55** [comment]
... long discussion ...
I would like to see some roadmap or a clear 'NO'.
Sorry to be undiplomatic.

BTW: very interesting discussions [here](https://github.com/aspnet/Logging/issues/332) and [here](https://github.com/aspnet/Logging/issues/328) , thanks @cwe1ss, unfortunately it seems no one is willing to accept your proposal.

**Comment by manikrish** [comment]
@cwe1ss, @Ed55   Thanks for your offer and apologies for the delay in response. We would gladly accept any community contributions to add .net 4.6 support to SLAB.

**Comment by ryanspletzer** [comment]
What type of tasks would need to be completed to enable .NET 4.6 support?

**Comment by bennage** [comment]
@ryanspletzer In full transparency, we're trying to figure out what the roadmap should be. We won't have an answer though until the week of April 7th. Please feel free to bump the thread if we haven't posted by then.

**Comment by YoupHulsebos** [comment]
@bennage bumping thread (as requested). Intrested in an update :)

**Comment by ryanspletzer** [comment]
Bueller?

**Comment by bennage** [comment]
@ryanspletzer @YoupHulsebos My apology for the delay. Here's our current situation.

We do not have a roadmap for Semantic Logging. We currently do not have any resources assigned to it. Our team believes in the importantance structured logging and we keep hoping to return this project, but other activities keep getting prioritized above it. 

I realize that this is disappointing and frustrating, but I prefer to be transparent with you about the situation. If you have further questions, comments, proposals, or criticisms, please feel free to share them.

**Comment by YoupHulsebos** [comment]
Thanks for the update. We're considering moving away from semantic-logging if thats the case.

**Comment by neuecc** [comment]
Thank you for update status.
I've decided all our production codes replace SLAB with our inhouse logger and keep improve it, EtwStream - https://github.com/neuecc/EtwStream
Of course, SLAB was a great concept and great implementation, SLAB was supported our logging system.
Thank you very much.

**Comment by bennage** [comment]
I understand and we appreciate the positive comments. I am now investigating a plan for an official .NET 4.6 release. However, I won't have anything definitive until after mid-June. We also have several other higher priorities, so if we do pursue the release it will take a month or two to be ready.

**Comment by Alex-Boo** [comment]
any updates?

**Comment by bennage** [comment]
@Alex-Boo My apologies for the delay. We're putting together a plan right now.

**Comment by bennage** [comment]
Just a quick update. We're putting together a roadmap for a maintenance release. We'll link to it here as soon as it's ready. We plan to publish an updated NuGet  package.

**Comment by neraath** [comment]
Thanks for the update @bennage . We eagerly await that roadmap.

**Comment by bennage** [comment]
@neraath See #91.

**Comment by mekoda** [comment]
Closing (as this is now scoped in #91 as the first milestone from v2.1 release).

**Comment by bennage** [comment]
Please see the note on #91. We are no longer working on Semantic Logging.
