### ISSUE TITLE
Error installing logging service from console application

### ISSUE THREAD

**Issue by nathvi** [mspnp/semantic-logging#65]
For whatever reason, I cannot install this service. Here's what I did. 1. Created a new console application in visual studio 2015.

Opened the NuGet Package Manager, and installed the EnterpriseLibrary.SemanticLogging.Service package. In the description it reads "... This package contains an out-of-proc Windows Service for SLAB.

Opened the Visual Studio Command Prompt (2010). Changed the directory to the location: C:\Users\User\Documents\visual studio 2015\Projects\SampleLoggingApp\packages\EnterpriseLibrary.SemanticLogging.Service.2.0.1406.1\tools

Ran the command: install-packages.ps1

A notepad file opened, named: install-packages.ps1

Ran the command: SemanticLogging-svc.exe -install

I got back an error message. Not really sure what it means:
"Enterprise Library Semantic Logging Service v2.0.1406.1
Microsoft Enterprise Library
Microsoft Corporation

Running a transacted installation.

Beginning the Install phase of the installation.
See the contents of the log file for the C:\Users\User\Documents\Visual Stud
io 2015\Projects\SampleLoggingApp\packages\EnterpriseLibrary.SemanticLogging.Ser
vice.2.0.1406.1\tools\SemanticLogging-svc.exe assembly's progress.
The file is located at C:\Users\User\Documents\Visual Studio 2015\Projects\S
ampleLoggingApp\packages\EnterpriseLibrary.SemanticLogging.Service.2.0.1406.1\to
ols\SemanticLogging-svc.InstallLog.
Installing assembly 'C:\Users\User\Documents\Visual Studio 2015\Projects\Sam
pleLoggingApp\packages\EnterpriseLibrary.SemanticLogging.Service.2.0.1406.1\tool
s\SemanticLogging-svc.exe'.
Affected parameters are:
   logtoconsole =
   assemblypath = C:\Users\User\Documents\Visual Studio 2015\Projects\Sample
LoggingApp\packages\EnterpriseLibrary.SemanticLogging.Service.2.0.1406.1\tools\S
emanticLogging-svc.exe
   logfile = C:\Users\User\Documents\Visual Studio 2015\Projects\SampleLoggi
ngApp\packages\EnterpriseLibrary.SemanticLogging.Service.2.0.1406.1\tools\Semant
icLogging-svc.InstallLog
An exception occurred while trying to find the installers in the C:\Users\User\Documents\Visual Studio 2015\Projects\SampleLoggingApp\packages\EnterpriseLib
rary.SemanticLogging.Service.2.0.1406.1\tools\SemanticLogging-svc.exe assembly.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the
 requested types. Retrieve the LoaderExceptions property for more information.
Aborting installation for C:\Users\User\Documents\Visual Studio 2015\Project
s\SampleLoggingApp\packages\EnterpriseLibrary.SemanticLogging.Service.2.0.1406.1
\tools\SemanticLogging-svc.exe.

An exception occurred during the Install phase.
System.InvalidOperationException: Unable to get installer types in the C:\Users\
User\Documents\Visual Studio 2015\Projects\SampleLoggingApp\packages\Enterpr
iseLibrary.SemanticLogging.Service.2.0.1406.1\tools\SemanticLogging-svc.exe asse
mbly.
The inner exception System.Reflection.ReflectionTypeLoadException was thrown wit
h the following error message: Unable to load one or more of the requested types
. Retrieve the LoaderExceptions property for more information..

The Rollback phase of the installation is beginning.
See the contents of the log file for the C:\Users\User\Documents\Visual Stud
io 2015\Projects\SampleLoggingApp\packages\EnterpriseLibrary.SemanticLogging.Ser
vice.2.0.1406.1\tools\SemanticLogging-svc.exe assembly's progress.
The file is located at C:\Users\User\Documents\Visual Studio 2015\Projects\S
ampleLoggingApp\packages\EnterpriseLibrary.SemanticLogging.Service.2.0.1406.1\to
ols\SemanticLogging-svc.InstallLog.
Rolling back assembly 'C:\Users\User\Documents\Visual Studio 2015\Projects\S
ampleLoggingApp\packages\EnterpriseLibrary.SemanticLogging.Service.2.0.1406.1\to
ols\SemanticLogging-svc.exe'.
Affected parameters are:
   logtoconsole =
   assemblypath = C:\Users\User\Documents\Visual Studio 2015\Projects\Sample
LoggingApp\packages\EnterpriseLibrary.SemanticLogging.Service.2.0.1406.1\tools\S
emanticLogging-svc.exe
   logfile = C:\Users\User\Documents\Visual Studio 2015\Projects\SampleLoggi
ngApp\packages\EnterpriseLibrary.SemanticLogging.Service.2.0.1406.1\tools\Semant
icLogging-svc.InstallLog
An exception occurred while trying to find the installers in the C:\Users\User\Documents\Visual Studio 2015\Projects\SampleLoggingApp\packages\EnterpriseLib
rary.SemanticLogging.Service.2.0.1406.1\tools\SemanticLogging-svc.exe assembly.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the
 requested types. Retrieve the LoaderExceptions property for more information.
Aborting installation for C:\Users\User\Documents\Visual Studio 2015\Project
s\SampleLoggingApp\packages\EnterpriseLibrary.SemanticLogging.Service.2.0.1406.1
\tools\SemanticLogging-svc.exe.
An exception occurred during the Rollback phase of the System.Configuration.Inst
all.AssemblyInstaller installer.
System.InvalidOperationException: Unable to get installer types in the C:\Users\
User\Documents\Visual Studio 2015\Projects\SampleLoggingApp\packages\Enterpr
iseLibrary.SemanticLogging.Service.2.0.1406.1\tools\SemanticLogging-svc.exe asse
mbly.
The inner exception System.Reflection.ReflectionTypeLoadException was thrown wit
h the following error message: Unable to load one or more of the requested types
. Retrieve the LoaderExceptions property for more information..
An exception occurred during the Rollback phase of the installation. This except
ion will be ignored and the rollback will continue. However, the machine might n
ot fully revert to its initial state after the rollback is complete.

The Rollback phase completed successfully.

The transacted install has completed.
SemanticLogging-svc Error: 2 : The installation failed, and the rollback has been performed."

**Comment by mekoda** [comment]
Hi @nathvi, one comment about the process:

> Opened the Visual Studio Command Prompt (2010). Changed the directory to the location: C:\Users\User\Documents\visualstudio2015\Projects\SampleLoggingApp\packages\EnterpriseLibrary.SemanticLogging.Service.2.0.1406.1\tools
> 
> Ran the command: install-packages.ps1
> 
> A notepad file opened, named: install-packages.ps1
> 
> Ran the command: SemanticLogging-svc.exe -install

Given that ```install-packages.ps1``` is a Powershell script, so you will need to run it in Powershell. Just open it, go to the script location and then run:
```
.\install-packages.ps1
```

This will install the dependencies.

**Comment by nathvi** [comment]
Ok, thank you.
