### ISSUE TITLE
JsonEventTextFormatter wrong DateTime value - utc agains local

### ISSUE THREAD

**Issue by Zawulon** [mspnp/semantic-logging#67]
Using : EnterpriseLibrary.SemanticLogging.OutOfService

JsonEventTextFormatter has no option to log in local time with time zone information. 
Expected result is Local time + timeoffset.
When giving timestamp format “yyyy-MM-ddTHH:mm:ss:fffzzz”, timeoffset information is ok, but time value is used as DateTime.UtcNow.
Should be DateTime.Now + timeoffset

**Comment by mekoda** [comment]
Hi @Zawulon,

Semantic Logging uses UTC by default, this is why the ```JsonEventTextFormatter``` does not present this functionality.

However, feel free to fork the repo, modify the code and add the feature you are looking for. Moreover, then you can propose it here with a pull request.
