### ISSUE TITLE
InspectAll error with WriteEventWithRelatedActivityId

### ISSUE THREAD

**Issue by brinko99** [mspnp/semantic-logging#76]
The following is producing an InspectAll error of:

> The number of WriteEvent arguments and event parameters are different in event name 'Event4'

```
[Event(103)]
public void Event4(string name, string value)
{
    WriteEventWithRelatedActivityId(103, Guid.NewGuid(), name, value);
}
```

I would not expect this to cause an error.  This however produces no error:

```
[Event(103)]
public void Event4(string name)
{
    WriteEventWithRelatedActivityId(103, Guid.NewGuid(), name);
}
```
Any ideas? Thanks.

.NET 4.6.1
SLAB: 2.0.1406.1

**Comment by arambarri** [comment]
Hi @brinko99

Thanks for the report. We were able to reproduce the error using your code.

However, you are not using the feature properly. Here the documentation related to [EventSource.WriteEventWithRelatedActivityId Method](https://msdn.microsoft.com/en-us/library/system.diagnostics.tracing.eventsource.writeeventwithrelatedactivityid(v=vs.110).aspx).

Your ETW event method calling this function **must** follow these guidelines:
* Specify the first parameter as a Guid named relatedActivityId.
* Specify either Send or Receive as the EventAttribute.Opcode property.
* Call WriteEventWithRelatedActivityId passing in the event ID, followed by the related ID GUID, followed by all the parameters the event method is passed, in the same order.

For example, the following code is working, 

``` 
namespace ETWEventSourceAnalyzer
{

    [EventSource(Name = "Sample")]
    public sealed class Sample : EventSource
    {
        // Define singleton instance
        public static Sample Log = new Sample();

        [Event(103, Task = Tasks.MyTask, Opcode = EventOpcode.Send)]
        public void Event4(Guid relatedActivityId,string name, string value)
        {
            WriteEventWithRelatedActivityId(103, relatedActivityId, name, value);
        }
        private static class Tasks
        {
            public const EventTask MyTask = (EventTask)2048;
        }
    }
    public class Program
    {
        static void Main(string[] args)
        {
           EventSourceAnalyzer.InspectAll(Sample.Log);
        }
    }
}
```

**Comment by brinko99** [comment]
Excellent thank you.

I had previously included the parameter for the related activity ID but removed it while trying to simplify the repo. It turns out that it was the missing Opcode that was the root of my problem.

However, I'll note that _with _the relatedActivityId and _missing _the Opcode, EventSourceAnalyzer complains about a mismatch of argument and parameters. This is very confusing, it would be much more handy for the analyzer to recognize the missing Send or Receive opcode.

Thanks.
