### ISSUE TITLE
 ETW manifests not updated with new Event details

### ISSUE THREAD

**Issue by brinko99** [mspnp/semantic-logging#78]
When using the out-of-proc service, Event details are only cached in the ETW manifest the first time the event is seen. Changes to the event properties, Level, Message, etc will not propagate to the manifest and thus the old properties are used even though the new properties are compiled into the EventSource assembly.

This is sure to cause _everyone_ who uses the out-of-proc service hours of frustration. This has been noted by others:
- https://github.com/mspnp/semantic-logging/issues/57
- http://stackoverflow.com/q/31626076/84522

Issue 57 was closed due to lack of activity but should have been filed as a bug IMHO. At the very least, every SLAB document dealing with the out-of-proc service should spell this out explicitly. The only hint at the caching behavior of the manifests I've found comes from here:
[Collecting events from multiple processes](https://msdn.microsoft.com/en-us/library/dn774983%28v=pandp.20%29.aspx#_Toc393368644)

> The trace event service in the Out-of-Process Host automatically manages updates to event source manifests, and it will always use the highest version. Therefore, you should add version information to your event source classes, and ensure that changes are only additive, in order to avoid affecting the logging behavior of the other applications.

It's pretty easy to miss that especially since it's in the section regarding multiple processes and the issue crops up during development of a single process solution. The solution to this issue appears to be versioning. Under [Versioning your EventSource Class](https://msdn.microsoft.com/en-us/library/dn440729%28v=pandp.60%29.aspx#sec13) we see:

> If you do need to modify your EventSource class, you should restrict your changes to adding methods to support new log messages, and adding overloads of existing methods (that would have a new event ID). You should not delete or change the signature of existing methods.

Again it is talking about having multiple instances of the EventSource in different processes and there is no mention of actual versioning.

I've found that by applying the EventAttribute.Version to my Event (presumably works for EventSource as well), the manifest is updated as the version is incremented. This should be stated somewhere in the documentation.

**Comment by bennage** [comment]
Please see the note on #91. We are no longer working on Semantic Logging.
