### ISSUE TITLE
Formatted message not formatted when run with out-of-proc service

### ISSUE THREAD

**Issue by brinko99** [mspnp/semantic-logging#79]
I find that if my Event uses a custom format for the message, the formatting isn't processed when running through the out-of-proc service.

The following event produces a formatted message (hex value) when run in proc with the FlatFileLog, yet produces the literal value {0:X8} when run through the flatFileSink via the service. If the format is simply {0}, the actual int value is logged as one would expect.

Any ideas what's going on?

```
[Event(110, Message = "{0:X8}", Level = EventLevel.Informational)]
public void Event110(int value)
{
    WriteEvent(110, value);
}
```
```
<flatFileSink name="flatFileEventSink"  fileName="log.txt">
  <sources>
    <eventSource name="SystemEvents" level="Verbose"/>
  </sources>
  <eventTextFormatter header="+=========================================+"/>
</flatFileSink>
```

**Comment by arambarri** [comment]
Hi @brinko99,

Thank for your inquiry.

The issue is because of the event source translation from .net to windows. 

If you use other Listener different from SLAB (For example PerfView), you will see the same effect

```
    [EventSource(Name = "Sample")]
    public sealed class Sample : EventSource
    {
        public static Sample Log = new Sample();

        [Event(110, Message = "{0:X8}", Level = EventLevel.Informational)]
        public void Event110(int value)
        {
            WriteEvent(110, value);
        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            Sample.Log.Event110(12);
        }
    }
```
![sample](https://cloud.githubusercontent.com/assets/12565389/15194735/df0c21ae-179a-11e6-9518-eb0ee3087994.PNG)

In out-of-process scenario, the event go through Windows ([Figure 1 and 2](https://msdn.microsoft.com/en-us/library/dn440729(v=pandp.60).aspx))

**Comment by brinko99** [comment]
I see. If I'm understanding you right, ETW uses the formatted message placeholders, {0}{1}...{n} as simple find-and-replace placeholders whereas a SLAB listener so happens to process those with String.Format().

The only documentation regarding the format placeholders I've found is here: [Specifying the event and its payload](https://msdn.microsoft.com/en-us/library/dn774985(v=pandp.20).aspx#_Specifying_the_event)

> An event message is a human readable version of the payload information, and you control the format using the Message parameter of the Event attribute. For example, the Startup method in the MyCompanyEventSource example class always writes the string “Starting up” to the log when invoked. The PageStart method (repeated below) writes a message to the log, substituting the values of the ID and url parameters for the two placeholders in the Message attribute string.

I guess it was I who assumed that the formatted message would honor standard .NET string formats. Given that the SLAB listener does, I designed my events around this feature only to find later that the out-of-proc service is different.

Additional documentation in this area would be appropriate.

How can I work around this limitation? My first thought was to format the int into a hex string in the event itself: 

[Event(110, Message = "{0}", Level = EventLevel.Informational)]
public void Event110(int value)
{
    string valueString = $"{value:X8}";
    WriteEvent(110, valueString);
}

This doesn't work. It seems that the type passed into WriteEvent must be the same as the parameter type of my Event (though EventSourceAnalyzer  doesn't catch this). Perhaps an upcoming release of SLAB could include as part of the EventEntry the raw event schema Message value ("{0:X8}" in my case). This would allow the formatter to always use String.Format(). Please consider this for the roadmap.

How can I perform this simple transformation? Is there anything I'm overlooking?

**Comment by arambarri** [comment]
Hi @brinko99,

The client application with the EventSource is not related to SLAB. It is .Net EventSouce implementation which using a Windows API send the information to the OS. Here, the event goes beyond the .Net platform where the placeholder capabilities are different.

SLAB is a ETW listener, and PerfView is another. 

The event method has to have the sequence of parameters of the same type, and they has to be passed in the same order to the WriteEvent method (Last table, [Same type arguments order mismatch](https://msdn.microsoft.com/en-us/library/dn774985(v=pandp.20).aspx#_Checking_an_event)).

You can also include a non-event method in your event source class that performs some pre-processing, transforming, or formatting of data before calling an event method.

The IsEnabled method could help to improve performance if you are using the costly overload of the WriteMethod that includes a params object[] parameter or you are performing some pre-processing, transforming, or formatting (for example, serializing an object), you may not need to execute if the event is not enabled.

```
    [EventSource(Name = "Sample")]
    public sealed class Sample : EventSource
    {
        public static Sample Log = new Sample();

        [Event(110, Message = "{0}", Level = EventLevel.Informational, Keywords = Keywords.Any)]
        private void Event110(string value)
        {
            WriteEvent(110, value);
        }

        [NonEvent]
        public void Event110(int value)
        {
            if (this.IsEnabled(EventLevel.Informational, Keywords.Any))
            {
                string valueString = string.Format("{0:X8}", value);
                this.Event110(valueString);
            }
        }

        public class Keywords
        {
            public const EventKeywords Any = (EventKeywords)1;
        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            Sample.Log.Event110(12);
        }
    }
```

The EventEntry is created from Microsoft.Diagnostics.Tracing.TraceEvent received, where the message is already Formatted.

**Comment by brinko99** [comment]
Thanks for the updated.

I had considered a workaround similar to what you proposed however I was unaware of the NoEvent attribute. That should solve my issue.

Please consider improving the documentation in these areas.

Thanks again.
