### ISSUE TITLE
Upgrade Microsoft.WindowsAzure.Storage in SemanticLogging.WindowsAzure project

### ISSUE THREAD

**Issue by robichaud** [mspnp/semantic-logging#81]
SemanticLogging.WindowsAzure references a very old version of Microsoft.WindowsAzure.Storage. Breaking changes in Microsoft.WindowsAzure.Storage v7.0 prevent redirecting.

**Comment by ohadschn** [comment]
Seconded. This is what you get when you try using the new storage SDK: 

> Exception thrown: 'System.MissingMethodException' in Microsoft.Practices.EnterpriseLibrary.SemanticLogging.WindowsAzure.dll
> 
> Additional information: Method not found: 'Void Microsoft.WindowsAzure.Storage.Table.CloudTableClient.set_RetryPolicy(Microsoft.WindowsAzure.Storage.RetryPolicies.IRetryPolicy)'.

Related SO discussion: http://stackoverflow.com/questions/38141018/how-can-i-track-the-source-of-exception-on-trying-to-set-azure-sink-for-a-listen

**Comment by bennage** [comment]
We're in the process of scheduling this work. My apologies for the lengthy delay.

**Comment by robertmacgrogan** [comment]
I ran into this today when trying to upgrade to all of the latest Azure tools and had to do my own patch to fix the problem. The fix is trivial.

Just replace line 69 in WindowsAzureTableSink with the following:

            client.DefaultRequestOptions = new TableRequestOptions
            {
                RetryPolicy = new ExponentialRetry(TimeSpan.FromSeconds(5), 7),
                MaximumExecutionTime = TimeSpan.FromSeconds(10)
            };

This will compile. However, I have not yet been able to test because upgrading azure tools also blows up lots of other things. I'll post later when I see this working successfully.

**Comment by bennage** [comment]
@robertmacgrogan thanks!

**Comment by robertmacgrogan** [comment]
I wanted to report that I finally was able to test and my fix as reported above works just fine. Not relevant here, but interesting to note that latest version of Microsoft.AspNet.SignalR.ServiceBus had the exact same issue.

Thanks.

**Comment by robichaud** [comment]
@paulirwin Any idea when you will release an updated NuGet package?

**Comment by NBelham** [comment]
For me I downgraded and that solved my issue
`<package id="WindowsAzure.Storage" version="3.0.3.0" targetFramework="net45" />`
