### ISSUE TITLE
WindowsAzureTableSink : PartitionKey is 2 hours behind when running on "BST"

### ISSUE THREAD

**Issue by aboobolaky** [mspnp/semantic-logging#87]
Hi,

Re: WIndowsAzureTableSink

The EventDate (as well as timestamp) are UTC-based.
When the partition key is generated in DateTimeExtensions.cs (either normal WAD style gen or reverse timestamped), the eventdate is passed in as a parameter and a datetime object is created out of it, elimating the seconds and most importantly the DateTimeKind.

The upshot of this is calling ToUniversalTime() again on a machine that is already on BST causes the partition key to be behind by 2 hours (instead of 1hr) 
 
`public static string GeneratePartitionKeyReversed(this DateTime dateTime)        {`  
`           dateTime = dateTime.AddMinutes(-1D);`  
`          var pk = new DateTime(dateTime.Year, dateTime.Month, dateTime.Day, dateTime.Hour, ``     dateTime.Minute, 0);`  
`            return GetTicksReversed(pk);`  
`        } `  

` internal static string GetTicksReversed(this DateTime dateTime)`
 `       {`
          `  return (DateTime.MaxValue - dateTime.ToUniversalTime()).Ticks.ToString("d19", CultureInfo.InvariantCulture);`
`       }`

**example**  
(EventDate is in UCT and events are being collected on a machine which is on BST)

Machine Time : 2016-06-22T14:12:14.6980463Z
EventDate :       2016-06-22T13:12:14.6980463Z (OK)
Timestamp:       2016-06-22T13:12:53.6490621Z (OK)

Partition Key : 2519357033399999999

if we convert the partition key back to it's orginal state ,  the value is 22/06/2016 12:11:00 when in fact it should be "22/06/2016 13:11:00" (which should be 1 minute behind the EventDate)

i'll create a pull request and will submit when this bug is fixed

Regards
Aboo

**Comment by aboobolaky** [comment]
Hi,
Can a new nuget package be generated off this merge?

Regards
Aboo

**Comment by mekoda** [comment]
Hi Aboo, 

We plan to release a new package version soon (see https://github.com/mspnp/semantic-logging/issues/64#issuecomment-242461667 for more details).
