### ISSUE TITLE
Proposed Roadmap

### ISSUE THREAD

**Issue by bennage** [mspnp/semantic-logging#91]
First, my profuse apologies for the lack of communication. 

Secondly, our primary motivation for this roadmap is to assist users that have already taken a dependency on the library. We will focus our efforts on items that impact current users.

[**v2.1**](https://github.com/mspnp/semantic-logging/milestone/1)
- Update to .NET 4.6
- Update TraceEvent NuGet references
- Update Azure SDK references 
- Bug fixes ([look for issues tagged with the milestone](https://github.com/mspnp/semantic-logging/milestone/1))

After v2.1, we are _considering_ the following:
- .NET Core Support
- Integration with [ASP.NET logging](https://github.com/aspnet/Logging/) - _What should this look like?_
- Support for [EventSource Activity](https://blogs.msdn.microsoft.com/vancem/2015/09/14/exploring-eventsource-activity-correlation-and-causation-features/) (replacing current correlation support)
- Support for [Dynamically Defined events](https://blogs.msdn.microsoft.com/vancem/2015/10/02/dynamically-defined-events-in-eventsource-v4-6/) #44 #86 
- Support for [Rich Data Payloads](https://blogs.msdn.microsoft.com/vancem/2015/09/20/rich-payload-data-in-eventsource-v4-6/)
- Support for Channels
- Address caching of manifests when running out-of-procces 
- EventHub sink

We are in the process of getting engineering resource assigned to 2.1. We will post a new date after they evaluate the backlog for 2.1. My goal is to have it release before the end of October.

Feedback?

**Comment by neraath** [comment]
As far as ASP.Net Logging, my vote would be to focus on OWIN. Our shop is exclusively ASP.Net Web API via OWIN on Service Fabric, a prime candidate for ETW events. Our biggest problems that we're tackling right now are:

- Tracking requests and responses through our APIs
- Understanding what's happening in the ASP.Net Web API OWIN middleware, especially when exceptions happen. 

Both of the above are not unique to us - it's a fairly commonplace request. Something to help bootstrap this would be immensely useful.

We're also Sinking out to Application Insights. The telemetry we gain through that is truly astounding. I'd suggest between EventHub and AI, go AI.

**Comment by Expecho** [comment]
I've already completed an EventHub sink. Maybe we can collaborate on that one? See https://github.com/DeHeerSoftware/SemanticLogging.EventHub .

@neraath What we do is we log to the EventHub sink and from there fan out to AI. The data retention of AI is to short for us.

**Comment by cwe1ss** [comment]
There's already an EventSource logger provider for the new ASP.NET logging library in their dev-branch: https://github.com/aspnet/Logging/tree/dev/src/Microsoft.Extensions.Logging.EventSource

Not sure when they will release it though - maybe with ASP.NET Core 1.1

**Comment by maxal1917** [comment]
@Expecho Why have you decided to use EventHub and then put it to AI instead of using sink to AI.

Also, do you populate custom properties in AI from payload? I want to populate them and trying to see if we need to write custom code or there is something available that does it already.

Thanks.

**Comment by Expecho** [comment]
@maxal1917 We decided to send all telemetry to the EventHub and from there store some of them in blob storage / table storage for long term analysis and redirect some to AI. The data retention in AI for raw data is only 7 days and with our multitenant app we are quickly reaching the 15M datapoints.

We use the SLAB also to log usage and custom metrics of our app and we want to have numbers about performance, stability and usage over different releases. Using blob/table storage allows us to build up statistics over a longer period.

By sending all data to only the EventHub and not to AI and table/blob storage directly we reduce the amount of traffic send by the application.

**Comment by maxal1917** [comment]
@Expecho I'm exactly with you. My comments about sink were only in the context of sending logs to traces only. For page requests, dependencies, metrcs etc. AI SDK is still going to be used directly for the app. 

One more question if I may, do you use stream analytics on the other side of Event Hub or just your own listener?

**Comment by Expecho** [comment]
@maxal1917 We have created our own listener by implementing the IEventProcessor interface and using the EventProcessorHost. It gives us more control about the destinations. When we started the output options of stream analytics where too limited.

**Comment by bennage** [comment]
Thanks everyone, this is good feedback.
I really like the idea of integration with AI. Right now, we're just working on scheduling engineering resources for 2.1. This includes setting up an appropriate test plan.

**Comment by bennage** [comment]
For those of you that have created projects around SL, please see #92 .

**Comment by luisfco** [comment]
any news ??

**Comment by bennage** [comment]
We've had difficulty getting the engineering resources scheduled. In full disclosure, no one from the original SL team is still working in p&p. Our original plan was to bring in some vendors who had worked on it previously. However, that hasn't worked out. 🙁 

In addition, another project has started, [EventFlow](https://github.com/Azure/diagnostics-eventflow), and  we think it is suitable replacement for SL.

Our engineering manager (@RohitSharma-pnp) is pursuing a different way to get the engineering resources, but he estimates two weeks before he'll have a timeline.

**Comment by bdongus** [comment]
Thanks for the efforts and update.

**Comment by kwaclaw** [comment]
@bennage The EventFlow project seems to be targeted at Azure only.

**Comment by bennage** [comment]
I'm sad to announce that we will not working on future releases of Semantic Logging.
We had sincere intentions, but as you can tell from the lack of activity on this repository, we have been unable to devote the appropriate resources to the project. 
If you are interested, please feel free to fork the repository and to carry it forward.

**Comment by cwe1ss** [comment]
Thanks for the honest update!

**Comment by kwaclaw** [comment]
Is this a good alternative:  https://github.com/neuecc/EtwStream ?

**Comment by whizlingo** [comment]
Or may be https://github.com/Azure/diagnostics-eventflow ?

**Comment by nblumhardt** [comment]
Or also: https://serilog.net (originally inspired by Semantic Logging!)

Thanks for breaking new ground with this project 👍
