### ISSUE TITLE
`EventSchema.EventName` always concatenates the Opcode name to the Task name, even if no OpCode was specified

### ISSUE THREAD

**Issue by ohadschn** [mspnp/semantic-logging#95]
This means that all events whose `Opcode` wasn't specified end up with an "Info" suffix (as `EventOpcode.Info` is the enum's default). For example an event named `Foo` with no Opcode (and no `Task` for that matter) specified will show up as `FooInfo` in the event schema (specifically, as observed in custom sinks).

It is my understanding that in such cases, only the task name (which is equivalent to the method's name if it wasn't explicitly specified), should be used. See: http://blogs.msmvps.com/kathleen/2014/01/24/how-are-event-parameters-best-used-to-create-an-intuitive-custom-evnetsourcetrace/.

**Comment by ohadschn** [comment]
BTW, if you look at the code for `System.Diagnostics.Tracing.EventAttribute` you'll notice that it makes a distinction between `Opcode.Info` (the enum's default) and an Opcode that wasn't set at all (it has a boolean `m_opcodeSet` field for this purpose).

**Comment by bennage** [comment]
Please see the note on #91. We are no longer working on Semantic Logging.
